//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_books
    {
        public int book_id { get; set; }
        public string book_name { get; set; }
        public string book_author { get; set; }
        public double book_edition { get; set; }
        public double book_price { get; set; }
        public int book_qunatity { get; set; }
        public int user_id { get; set; }
    
        public virtual tbl_user tbl_user { get; set; }
    }
}
